client_config_backend: settings
client_config:
  client_id: 579886165414-nd3od2sded7qrc4a5tr646k7dqh9r1o4.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
